databases:
  - name: tildeblog
    plan: free
    databaseName: tildeblogdb
    user: tildeblog

services:
  - type: web
    plan: free
    name: tildeblog
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "cd django_site && python -m gunicorn django_root.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_root.render_settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4